### ISSUE TITLE
Issue to trigger new releases

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJTSVDInterface.jl#7]
@JuliaRegistrator register branch = master

cc @pazzo83

**Comment by ablaom** [comment]
Not auto registering for some reason. Here's the PR:

https://github.com/JuliaRegistries/General/pull/42274

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- Add `rng` to the `TSVD` model to specify a random number generator or `MersenneTwister` seed (#8) @pazzo83

**Comment by pazzo83** [comment]
@JuliaRegistrator register branch=master

release notes:

- Fix bug with `rng` parameter on the `TSVDTransformer` (https://github.com/JuliaAI/MLJTSVDInterface.jl/pull/10)

**Comment by pazzo83** [comment]
@JuliaRegistrator register branch=master

release notes:

Fix bug with rng parameter on the TSVDTransformer (fix minor bug with new RNG parameter, fix issue with transformer not … #10)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- Remove ScientificTypesBase.jl as dependency and bump Julia version to ^0.6 (#12)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliiaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master
